// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package models

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserBio struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Fname                string   `protobuf:"bytes,2,opt,name=Fname,proto3" json:"Fname,omitempty"`
	Lname                string   `protobuf:"bytes,3,opt,name=Lname,proto3" json:"Lname,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserBio) Reset()         { *m = UserBio{} }
func (m *UserBio) String() string { return proto.CompactTextString(m) }
func (*UserBio) ProtoMessage()    {}
func (*UserBio) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserBio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserBio.Unmarshal(m, b)
}
func (m *UserBio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserBio.Marshal(b, m, deterministic)
}
func (m *UserBio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserBio.Merge(m, src)
}
func (m *UserBio) XXX_Size() int {
	return xxx_messageInfo_UserBio.Size(m)
}
func (m *UserBio) XXX_DiscardUnknown() {
	xxx_messageInfo_UserBio.DiscardUnknown(m)
}

var xxx_messageInfo_UserBio proto.InternalMessageInfo

func (m *UserBio) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserBio) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *UserBio) GetLname() string {
	if m != nil {
		return m.Lname
	}
	return ""
}

func (m *UserBio) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserBio) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Fname                string   `protobuf:"bytes,2,opt,name=Fname,proto3" json:"Fname,omitempty"`
	Lname                string   `protobuf:"bytes,3,opt,name=Lname,proto3" json:"Lname,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFname() string {
	if m != nil {
		return m.Fname
	}
	return ""
}

func (m *User) GetLname() string {
	if m != nil {
		return m.Lname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserPayload struct {
	Bio                  *UserBio `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPayload) Reset()         { *m = UserPayload{} }
func (m *UserPayload) String() string { return proto.CompactTextString(m) }
func (*UserPayload) ProtoMessage()    {}
func (*UserPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPayload.Unmarshal(m, b)
}
func (m *UserPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPayload.Marshal(b, m, deterministic)
}
func (m *UserPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPayload.Merge(m, src)
}
func (m *UserPayload) XXX_Size() int {
	return xxx_messageInfo_UserPayload.Size(m)
}
func (m *UserPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPayload.DiscardUnknown(m)
}

var xxx_messageInfo_UserPayload proto.InternalMessageInfo

func (m *UserPayload) GetBio() *UserBio {
	if m != nil {
		return m.Bio
	}
	return nil
}

func (m *UserPayload) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Users struct {
	User                 []*UserBio `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUser() []*UserBio {
	if m != nil {
		return m.User
	}
	return nil
}

type Username struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Username) Reset()         { *m = Username{} }
func (m *Username) String() string { return proto.CompactTextString(m) }
func (*Username) ProtoMessage()    {}
func (*Username) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *Username) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Username.Unmarshal(m, b)
}
func (m *Username) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Username.Marshal(b, m, deterministic)
}
func (m *Username) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Username.Merge(m, src)
}
func (m *Username) XXX_Size() int {
	return xxx_messageInfo_Username.Size(m)
}
func (m *Username) XXX_DiscardUnknown() {
	xxx_messageInfo_Username.DiscardUnknown(m)
}

var xxx_messageInfo_Username proto.InternalMessageInfo

func (m *Username) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*UserBio)(nil), "user.UserBio")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserPayload)(nil), "user.UserPayload")
	proto.RegisterType((*UserId)(nil), "user.UserId")
	proto.RegisterType((*Users)(nil), "user.Users")
	proto.RegisterType((*Username)(nil), "user.Username")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x4d, 0x5b, 0xe8, 0xf7, 0x31, 0x60, 0xa3, 0x1b, 0x63, 0x9a, 0x7a, 0x10, 0x7b, 0x30, 0xc4,
	0x43, 0x6b, 0xe0, 0xe6, 0x91, 0x08, 0x49, 0x8d, 0x07, 0x53, 0xc3, 0xc5, 0x5b, 0x61, 0xd7, 0xa6,
	0x49, 0xcb, 0x36, 0xbb, 0x45, 0xc2, 0xbf, 0x30, 0xfe, 0x62, 0x33, 0xbb, 0x94, 0x06, 0x14, 0x8f,
	0xde, 0xfa, 0xe6, 0xed, 0x9b, 0x37, 0x6f, 0x3a, 0x00, 0x2b, 0xc9, 0x44, 0x50, 0x0a, 0x5e, 0x71,
	0xd2, 0xc2, 0x6f, 0xef, 0x32, 0xe5, 0x3c, 0xcd, 0x59, 0xa8, 0x6a, 0xf3, 0xd5, 0x5b, 0xc8, 0x8a,
	0xb2, 0xda, 0xe8, 0x27, 0xfe, 0x1a, 0xfe, 0xcd, 0x24, 0x13, 0xe3, 0x8c, 0x13, 0x07, 0xcc, 0x88,
	0xba, 0x46, 0xdf, 0x18, 0x58, 0xb1, 0x19, 0x51, 0x72, 0x0e, 0xed, 0xe9, 0x32, 0x29, 0x98, 0x6b,
	0xf6, 0x8d, 0x41, 0x27, 0xd6, 0x00, 0xab, 0x4f, 0xaa, 0x6a, 0xe9, 0xaa, 0x02, 0xc4, 0x83, 0xff,
	0xd8, 0x46, 0x11, 0x2d, 0x45, 0xec, 0x30, 0x2a, 0x26, 0x45, 0x92, 0xe5, 0x6e, 0x5b, 0x2b, 0x14,
	0xf0, 0x3f, 0x0c, 0x68, 0xe1, 0x93, 0xbf, 0xb5, 0x45, 0x45, 0x99, 0x48, 0xb9, 0xe6, 0x82, 0xba,
	0xb6, 0x56, 0xd4, 0xd8, 0x7f, 0x84, 0x2e, 0xaa, 0x9f, 0x93, 0x4d, 0xce, 0x13, 0x4a, 0xae, 0xc0,
	0x9a, 0x67, 0x5c, 0x4d, 0xd6, 0x1d, 0x9e, 0x04, 0x6a, 0xaf, 0xdb, 0x5d, 0xc5, 0xc8, 0xec, 0xf5,
	0x32, 0x0f, 0x7a, 0xb9, 0x60, 0xe3, 0xdb, 0x88, 0x1e, 0xe6, 0xf3, 0x6f, 0xa1, 0x8d, 0x8c, 0x24,
	0xd7, 0xa0, 0xfe, 0x8f, 0x6b, 0xf4, 0xad, 0xef, 0x06, 0x8a, 0xf2, 0x6f, 0x9a, 0x7c, 0xe8, 0xb6,
	0xaa, 0xb3, 0x1a, 0xda, 0xad, 0xc6, 0xc3, 0x4f, 0x53, 0x8f, 0xfe, 0xc2, 0xc4, 0x7b, 0xb6, 0x60,
	0x24, 0x84, 0x5e, 0xcc, 0xd2, 0x4c, 0x56, 0x4c, 0xa8, 0x1d, 0x9f, 0x35, 0xcd, 0xb7, 0xe9, 0xbc,
	0x5e, 0x53, 0x8a, 0x28, 0xb9, 0x83, 0xce, 0x34, 0x5b, 0x52, 0x3d, 0xd8, 0x45, 0xa0, 0x2f, 0x26,
	0xa8, 0x2f, 0x26, 0x98, 0xe0, 0xc5, 0x78, 0xdd, 0x46, 0x22, 0x49, 0x08, 0x0e, 0x2a, 0xc6, 0x9b,
	0xdd, 0x80, 0x4e, 0x43, 0x23, 0xf6, 0xf6, 0x13, 0x91, 0x7b, 0x38, 0x7d, 0x60, 0x39, 0xab, 0xd8,
	0x2f, 0x92, 0x23, 0xce, 0x64, 0x04, 0xf6, 0xac, 0xa4, 0x49, 0xc5, 0x7e, 0x4a, 0x72, 0x44, 0x34,
	0x76, 0x5e, 0x7b, 0x61, 0x2a, 0xca, 0x45, 0x58, 0x70, 0xca, 0x72, 0x39, 0xb7, 0x15, 0x3f, 0xfa,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x84, 0x78, 0xd9, 0x49, 0x22, 0x03, 0x00, 0x00,
}
