version: '3'

services:
  user-service:
    build:
      context: ./../user-service
      dockerfile: Dockerfile
    ports:
      - 4000:8000
    depends_on:
      - postgres
    environment:
      GRPC_PORT: 5000
      DSN: host=postgres port=5432 user=ryanpujo password=oke dbname=users sslmode=disable timezone=UTC connect_timeout=20
    volumes:
      - ./../user-service:/app
  
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.dockerfile
    ports:
      - 4001:5001
    depends_on:
      - user-service
    environment:
      PORT: 8000
    volumes:
      - ./../broker-service:/app

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ryanpujo
      POSTGRES_PASSWORD: oke
      POSTGRES_DB: users
    ports:
      - 5432:5432
    volumes:
      - ./../user-service/sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql