// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"database/sql"
)

type Address struct {
	ID            int32          `json:"id"`
	UserID        sql.NullInt32  `json:"user_id"`
	StoreID       sql.NullInt32  `json:"store_id"`
	StreetAddress sql.NullString `json:"street_address"`
	City          sql.NullString `json:"city"`
	State         sql.NullString `json:"state"`
	Country       sql.NullString `json:"country"`
	ZipCode       sql.NullString `json:"zip_code"`
}

type Cart struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	ProductID sql.NullInt32  `json:"product_id"`
	Quantity  sql.NullInt32  `json:"quantity"`
	Price     sql.NullString `json:"price"`
}

type Category struct {
	ID               int32          `json:"id"`
	Name             sql.NullString `json:"name"`
	Description      sql.NullString `json:"description"`
	ParentCategoryID sql.NullInt32  `json:"parent_category_id"`
}

type Order struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	StoreID     sql.NullInt32  `json:"store_id"`
	OrderDate   sql.NullTime   `json:"order_date"`
	TotalAmount sql.NullString `json:"total_amount"`
	Status      sql.NullString `json:"status"`
}

type OrderItem struct {
	ID        int32          `json:"id"`
	OrderID   sql.NullInt32  `json:"order_id"`
	ProductID sql.NullInt32  `json:"product_id"`
	Quantity  sql.NullInt32  `json:"quantity"`
	Price     sql.NullString `json:"price"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ParentCategory struct {
	ID          int32          `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

type Product struct {
	ID          int32          `json:"id"`
	StoreID     sql.NullInt32  `json:"store_id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Price       sql.NullString `json:"price"`
	ImageUrl    sql.NullString `json:"image_url"`
	Stock       sql.NullInt32  `json:"stock"`
	CategoryID  sql.NullInt32  `json:"category_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Store struct {
	ID          int32          `json:"id"`
	StoreName   sql.NullString `json:"store_name"`
	Description sql.NullString `json:"description"`
	ContactInfo sql.NullString `json:"contact_info"`
	OwnerID     sql.NullInt32  `json:"owner_id"`
}

type User struct {
	ID        int32          `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     sql.NullString `json:"email"`
	Username  sql.NullString `json:"username"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
